export const constants = {
  DEFAULT_LIMIT: 40,
  DEFAULT_OFFSET: 0,
  DESCRIPTION_MAX_LENGTH: 500,
  URL_MAX_LENGTH: 2048,
  SLUG_MIN_LENGTH: 1,
  NAME_MIN_LENGTH: 1,
  PRICE_PRECISION: 10,
  PRICE_SCALE: 2,
  EXPIRATION_DAYS: 14,
  RPC_URL: process.env.RPC_URL || "http://localhost:3000/api/rpc",
  NOT_FOUND_STATUS: 404,
} as const;
